---
image: docker:git

before_script:
  - export COMMIT_TIME=$(git show -s --format=%cd --date=format:%Y%m%d-%H%m%S $CI_COMMIT_SHA)
  - export IMAGE_TAG=$COMMIT_TIME.${CI_COMMIT_SHA:0:7}
  - export DOCKER_BUILDKIT=1
stages:
  - build
  - test

include:
  - "/twitter-clone/.gitlab-ci.yml"
